# Tensor Debug Notebook

这个 notebook 基于 `tensor.py` 拆分而来，目的是让每一段 PyTorch 张量操作都可以单独运行、逐步观察和调试。

In [ ]:
import torch


## 1. Creating Tensors

In [ ]:
print(f"{'=' * 20} Creating Tensors {'=' * 20}")

zeros = torch.zeros((2, 3), dtype=torch.int32)
print("zeros:")
print(zeros)

ones = torch.ones((2, 3))
print("\nones:")
print(ones)

rand = torch.rand((2, 3))
print(torch.is_tensor(rand))
print("\nrand:")
print(rand)
print(f"Shape: {rand.shape}")
print(f"Dtype: {rand.dtype}")
print(f"Device: {rand.device}")
print(f"Requires Grad: {rand.requires_grad}")
print(f"Is CUDA: {rand.is_cuda}")

ones_like = torch.ones_like(rand)
print("\nones (ones_like rand):")
print(ones_like)

full = torch.full((2, 2), 7)
print("\nfull (full of 7):")
print(full)

eye = torch.eye(5)
print("\neye (5x5 identity matrix):")
print(eye)

reshape_1 = torch.arange(12).reshape((3, 4))
print("\nreshape (arange(12) reshaped to 3x4):")
print(reshape_1)

unsqueezed = torch.unsqueeze(reshape_1, dim=0)
print("\nUnsqueezed tensor (dim=0):")
print(unsqueezed)
print(f"Shape of unsqueezed tensor: {unsqueezed.shape}")

squeezed = torch.squeeze(reshape_1)
print("\nSqueezed tensor:")
print(squeezed)
print(f"Shape of squeezed tensor: {squeezed.shape}")

transpored = reshape_1.t()
print("\nTransposed tensor:")
print(transpored)

zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
rand:
tensor([[0.5356, 0.3027, 0.6073],
        [0.8672, 0.7063, 0.4332]])
torch.is_tensor(rand): True
rand.is_cuda: False

ones_like:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
full:
tensor([[7, 7],
        [7, 7]])
eye:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
reshape_1:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
unsqueezed:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])
squeezed:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## 2. Splitting and Concatenating Tensors

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original tensor:")
print(a)

b = torch.tensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("\nAnother tensor:")
print(b)

# unbind the tensors
unbind_a = torch.unbind(a, dim=0)
print("\nUnbound tensor a:")
for i, unbound in enumerate(unbind_a):
    print(f"Unbound {i}:")
    print(unbound)

# Split the tensor into 3 chunks along the first dimension
chunks = torch.chunk(a, 3, dim=0)
print("\nChunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:")
    print(chunk)

# Concatenate the chunks back together
concatenated = torch.cat(chunks, dim=0)
print("\nConcatenated tensor:")
print(concatenated)

hstacked = torch.hstack((a, b))
print("\nHorizontally stacked tensor:")
print(hstacked)

vstacked = torch.vstack((a, b))
print("\nVertically stacked tensor:")
print(vstacked)

stacked_0 = torch.stack((a, b), dim=0)
print("\nStacked tensor (dim=0):")
print(stacked_0)
print(f"Shape of stacked tensor: {stacked_0.shape}")

stacked_1 = torch.stack((a, b), dim=1)
print("\nStacked tensor (dim=1):")
print(stacked_1)
print(f"Shape of stacked tensor: {stacked_1.shape}")

stacked_2 = torch.stack((a, b), dim=2)
print("\nStacked tensor (dim=2):")
print(stacked_2)
print(f"Shape of stacked tensor: {stacked_2.shape}")

split_0 = torch.split(a, 1, dim=0)
print("\nSplit tensor (split size=1, dim=0):")
for i, split in enumerate(split_0):
    print(f"Split {i}:")
    print(split)

split_1 = torch.split(a, 2, dim=1)
print("\nSplit tensor (split size=2, dim=1):")
for i, split in enumerate(split_1):
    print(f"Split {i}:")
    print(split)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Another tensor:
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

Chunks:
Chunk 0:
tensor([[1, 2, 3]])
Chunk 1:
tensor([[4, 5, 6]])
Chunk 2:
tensor([[7, 8, 9]])

Concatenated tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Horizontally stacked tensor:
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])

Vertically stacked tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

Stacked tensor (dim=0):
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Shape of stacked tensor: torch.Size([2, 3, 3])

Stacked tensor (dim=1):
tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [16,

## 3. Basic Operations

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
print("Original tensor:")
print(a)

repeated = a.repeat(2, 3)
print("\nRepeated tensor (repeat(2, 3)):")
print(repeated)

tiled = a.tile((2, 3))
print("\nTiled tensor (tile((2, 3))):")
print(tiled)

b = torch.tensor([5, 6])
print("\nAnother tensor:")
print(b)
print("\nShape of b:")
print(b.shape)
# expand will not copy the data, and it can only be used to expand dimensions of size 1
expanded = b.unsqueeze(1).expand(2, 3)
print("\nExpanded tensor:")
print(expanded)

## 4. Indexing Tensors

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original tensor:")
print(a)

# basic indexing
print("\na[1:3, :]:")
print(a[1:3, :])

# boolean indexing
print("\na[a > 5]:")
print(a[a > 5])

# advanced indexing
print("\na[[0, 2], [1, 2]]:")
print(a[[0, 2], [1, 2]])

# indexing with ellipsis
print("\na[..., 1]:")
print(a[..., 1])

# indexing with new axis
print("\na[:, None, :]:")
print(a[:, None, :])

# gathering
indices = torch.tensor([[0, 1], [1, 2], [2, 0]])
print("\nIndices for gathering:")
print(indices)
print("\na.gather(1, indices):")
print(a.gather(1, indices))
print("\na.gather(0, indices):")
print(a.gather(0, indices))

# scattering
scatter_indices = torch.tensor([[0, 1], [1, 0], [2, 2]])
scatter_values = torch.tensor([[10, 20], [30, 40], [50, 60]])
print("\nIndices for scattering:")
print(scatter_indices)
print("\nValues for scattering:")
print(scatter_values)
a.scatter_(1, scatter_indices, scatter_values)
print("\na after scattering(1, scatter_indices, scatter_values):")
print(a)

# masking, mask will squeeze the dimensions of the output tensor, so the output will be 1D
mask = torch.tensor(
    [[True, False, True], [False, True, False], [True, False, True]]
)
print("\nMask for masking:")
print(mask)
print("\na[mask]:")
print(a[mask])

# indexing with torch.where
condition = a > 5
print("\nCondition for torch.where (a > 5):")
print(condition)
print("\ntorch.where(condition, a, torch.zeros_like(a)):")
print(torch.where(condition, a, torch.zeros_like(a)))